jobs:
  - job: BuildDotNet7_0
    displayName: 'Build final (net7.0, build)'
    timeoutInMinutes: 15
    pool:
      ${{ if eq(parameters.selfHosted, 'true') }}:
        name: ${{ parameters.windowsVmImage }}
      ${{ if eq(parameters.selfHosted, 'false') }}:
        vmImage: ${{ parameters.windowsVmImage }}
    variables:
      - name: DotnetBuildName
        value: 'net7.0'
    steps:
    - template: ../steps/dotnet.yml
    - template: ../steps/install-minvertool.yml
    - template: ../steps/download-snk.yml
    - template: ../steps/minverversion-override.yml
    - template: ../steps/restore.yml
    - template: ../steps/build-net.yml
      parameters:
        targetFramework: "net7.0"
    - template: ../steps/publish-artifact.yml
      parameters:
        artifactName: "productionSrc"

  - job: BuildDotNet6_0
    displayName: 'Build final (net6.0, build)'
    timeoutInMinutes: 15
    pool:
      ${{ if eq(parameters.selfHosted, 'true') }}:
        name: ${{ parameters.windowsVmImage }}
      ${{ if eq(parameters.selfHosted, 'false') }}:
        vmImage: ${{ parameters.windowsVmImage }}
    variables:
      - name: DotnetBuildName
        value: 'net6.0'
    steps:
    - template: ../steps/dotnet.yml
    - template: ../steps/install-minvertool.yml
    - template: ../steps/download-snk.yml
    - template: ../steps/minverversion-override.yml
    - template: ../steps/restore.yml
    - template: ../steps/build-net.yml
      parameters:
        targetFramework: "net6.0"
    - template: ../steps/publish-artifact.yml
      parameters:
        artifactName: "productionSrc"

  - job: PublishBuildArtifacts
    condition: succeeded()
    dependsOn:
    - BuildDotNet7_0
    - BuildDotNet6_0
    displayName: 'Store NuGet Packages for Production'
    timeoutInMinutes: 30
    pool:
      ${{ if eq(parameters.selfHosted, 'true') }}:
        name: ${{ parameters.windowsVmImage }}
      ${{ if eq(parameters.selfHosted, 'false') }}:
        vmImage: ${{ parameters.windowsVmImage }}
    variables:
      - name: ArtifactPackageName
        value: 'Production'
    steps:
    - template: ../steps/dotnet.yml
    - template: ../steps/install-minvertool.yml
    - template: ../steps/minverversion-override.yml
    - template: ../steps/publish-nuget.yml
      parameters:
        artifactName: "productionSrc"
        artifactPackages:
          - "net7.0"
          - "net6.0"